// Comprehensive assets repository for Ihenya Racing Game
export const assets = {
  heroCar: "/hero-car.png",
  characters: {
    jay: "/character-jay.png",
    ketch: "/character-ketch.png",
    aaron: "/character-aaron.png",
    bubbly: "/character-bubbly.png",
    kihunzit: "/character-kihunzit.png",
  },
  cars: {
    necromancer: "/car-necromancer.png",
    hero: "/hero-car.png",
    lamborghini: "https://images.pexels.com/photos/9814982/pexels-photo-9814982.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    bmw: "https://images.pexels.com/photos/17888840/pexels-photo-17888840.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    matatu: "https://images.pexels.com/photos/30661414/pexels-photo-30661414.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    subaru: "https://images.pexels.com/photos/16350062/pexels-photo-16350062.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  mechanics: {
    sodaBaridi: {
      name: "Soda Baridi",
      modder: "Head Modder: Njoro",
      specialty: "Cryo-Cooling & Twin-Turbochargers",
      tagline: "Cooling is our culture. Zero overheat under police fire.",
      color: "#22d3ee",
      tag: "01",
      portrait: "https://images.pexels.com/photos/3970340/pexels-photo-3970340.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      workshop: "https://images.pexels.com/photos/17552590/pexels-photo-17552590.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      reputation: 98,
      location: "Industrial Area, Nairobi",
    },
    mufasa: {
      name: "Mufasa Performance",
      modder: "Master Builder: Mufasa",
      specialty: "V8 Swaps & Heavy Torque Dynamics",
      tagline: "Power. Pride. Performance. Built for war.",
      color: "#f97316",
      tag: "02",
      portrait: "https://images.pexels.com/photos/16552856/pexels-photo-16552856.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      workshop: "https://images.pexels.com/photos/34337558/pexels-photo-34337558.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      reputation: 99,
      location: "Kariobangi Light Industries",
    },
    chemiChemi: {
      name: "Chemi Chemi Precision",
      modder: "Lead Engineer: Wanjiku",
      specialty: "ECU Decoders & Nitrous Telemetry",
      tagline: "We don't fix, we perfect. Clean code, unstoppable speed.",
      color: "#10b981",
      tag: "03",
      portrait: "https://images.pexels.com/photos/9607008/pexels-photo-9607008.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      workshop: "https://images.pexels.com/photos/4480505/pexels-photo-4480505.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      reputation: 97,
      location: "Westlands Underground Vault",
    },
    motoKali: {
      name: "Moto Kali Custom",
      modder: "Lead Fabricator: Kim",
      specialty: "Widebody Armor & Flamethrower Exhausts",
      tagline: "Heat on the streets. If it doesn't breathe fire, it's not ours.",
      color: "#e11d2a",
      tag: "04",
      portrait: "https://images.pexels.com/photos/4271641/pexels-photo-4271641.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      workshop: "https://images.pexels.com/photos/8986035/pexels-photo-8986035.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      reputation: 95,
      location: "Gikomba Secret Works",
    },
    dukaLaMods: {
      name: "Duka La Mods",
      modder: "Import King: Otieno",
      specialty: "Overseas Exotics & Stealth Radar Wraps",
      tagline: "If you can dream it, we smuggle and tune it.",
      color: "#a855f7",
      tag: "05",
      portrait: "https://images.pexels.com/photos/4129015/pexels-photo-4129015.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      workshop: "https://images.pexels.com/photos/4489776/pexels-photo-4489776.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      reputation: 96,
      location: "Mombasa Port Underground",
    },
  },
};
